### ISSUE TITLE
Pls create Lineageos 16 (android 9) for m5c

### ISSUE THREAD

**Issue by Franceschinie** [XRedCubeX/pie_kernel_m5c#1]

**Comment by XRedCubeX** [comment]
I have no plans to continue with the kernel right now

**Comment by XRedCubeX** [comment]
I have no plans to continue with the kernel right now

**Comment by Franceschinie** [comment]
Quando faresti una release di  questo https://github.com/XRedCubeX/android_device_meizu_m5c ?

**Comment by XRedCubeX** [comment]
> Quando faresti una release di questo https://github.com/XRedCubeX/android_device_meizu_m5c ?

Era il tentativo di una ROM ma per ora non ho piani di continuare lo sviluppo su questo dispositivo per motivo di tempo, conoscenze e disponibilità sorgenti.

It was an attempt at a ROM but for now I have no plans to continue development on this device due to time, knowledge and source availability.
